version: "3.7"

services:
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    networks:
      - monitoring_network
    volumes:
      - "influxdbvol:/var/lib/influxdb"

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - monitoring_network
    volumes:
      - "grafanavol:/var/lib/grafana"
    depends_on:
      - influxdb

networks:
  monitoring_network:

volumes:
  influxdbvol: {}
  grafanavol: {}